  #ej 6 grocery list app
shopping_list = ["meat,cheese"]
print("welcome to the  shopping list app ")
import datetime
time = datetime.datetime.now()
month = str(time.month)
day = str(time.day)
hour = str(time.hour)
minute =str(time.minute)
print("the time is " , time )
print("you currently have "+str(shopping_list)+"on your grocery list")
food1 = input("\n what more grocery would you like to add: ")
shopping_list.append(food1)
print(f"you have just  added: {food1}")
food2= input("do you wish another item? ")
shopping_list.append(food2)
print(f"you have just added: {food2}")
food3= input("what more would you like ")
shopping_list.append(food3)
print(f"you have just added: {food3}")
print(f"\nyour shopping list is {shopping_list}")
print(f"there is no  {food3} en la tienda")
food4= input("\nwhat other element would you like to add to your list? ")
shopping_list.remove(food3)
shopping_list.append(food4)
print(f"\nyour list is finalised {shopping_list} \nThank you for your shopping and Have a Great day!.")